// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "MLX Vision",
    platforms: [
        .iOS("26.0")
    ],
    products: [
        .iOSApplication(
            name: "MLX Vision",
            targets: ["AppModule"],
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .camera),
            accentColor: .presetColor(.orange),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "Camera Processing"),
                .photoLibrary(purposeString: "Photo Processing"),
                .incomingNetworkConnections(),
                .outgoingNetworkConnections(),
                .fileAccess(.userSelectedFiles, mode: .readWrite)
            ],
            appCategory: .developerTools
        )
    ],
    dependencies: [
        .package(path: "../..")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "MLXVision", package: "mlx-swift-vision")
            ],
            path: ".",
            linkerSettings: [
                .unsafeFlags(["-rpath", "@executable_path", "-rpath", "@executable_path/Frameworks"])
            ]
        )
    ],
    swiftLanguageVersions: [.v5]
)